#! /bin/sh

export PATH=/bin:/sbin:/usr/bin:/usr/sbin:.

mount -o remount,rw / # REMOUNT_ROOTFS_RW

# TODO(sledbetter): fix /tmp mounting so not needed
mkdir -p /tmp/dropbear

# Start all init scripts in /etc/init.d
# executing them in numerical order.
#
for i in /etc/init.d/S[56789]?* ;do

     # Ignore dangling symlinks (if any).
     [ ! -f "$i" ] && continue

     case "$i" in
	*.sh)
	    # Source shell script for speed.
	    (
		trap - INT QUIT TSTP
		set start
		. $i
	    )
	    ;;
	*)
	    # No sh extension, so fork subprocess.
	    $i start
	    ;;
    esac
done

# :TODO: (by kedong, don't mount usb yet.
#echo "Mounting USB stick"
#sleep 2
# mount /dev/sda1 /mnt/usb
#sleep 2
