#!/bin/sh

MODULE_PATH=/usr/lib/modules

# Populate the platform ID
PLAT=$(hnvram -r PLATFORM_NAME)
echo ${PLAT#PLATFORM_NAME=} > /etc/platform
chmod 444 /etc/platform

# Don't let SCHED_FIFO / SCHED_RR realtime threads get preempted
echo -1 > /proc/sys/kernel/sched_rt_runtime_us

# Set up NEXUS first since it applies PINMUX.
echo "Starting nexus"
[ -e ${MODULE_PATH}/nexus.ko ] && insmod ${MODULE_PATH}/nexus.ko
if [ -e ${MODULE_PATH}/bcmdriver.ko ]; then
  insmod ${MODULE_PATH}/bcmdriver.ko
  mknod /dev/brcm0 c 30 0
fi

# populate hdcp key
hnvram -br HDCP_KEY > /tmp/hdcp_key

# enhance the memory threshold to reclaim the memory earlier.
echo 16000 > /proc/sys/vm/min_free_kbytes
