#!/bin/sh

# Don't let SCHED_FIFO / SCHED_RR realtime threads get preempted
echo -1 > /proc/sys/kernel/sched_rt_runtime_us


echo "Starting mdev"
mdev -s

echo "/sbin/stbhotplug" > /proc/sys/kernel/hotplug

# Set up NEXUS, if present
echo "Starting nexus"
[ -e ${MODULE_PATH}/nexus.ko ] && insmod ${MODULE_PATH}/nexus.ko
