#!/bin/sh

RETVAL=0
PLATFORM=$(cat /etc/platform)

start() {
  if [ "$PLATFORM" = "GFMS100" ]; then
    babysit 5 sysmgr --interval 60000 2>&1 | logger -t sysmgr &
    RETVAL=$?
    return $RETVAL
  fi
}

stop() {
  pkill -x sysmgr
  RETVAL=$?
  return $RETVAL
}

restart() {
  stop
  start
}

case "$1" in
  start)
    start
  ;;
  stop)
    stop
  ;;
  restart)
    restart
  ;;
  *)
  echo "Usage: $0 {start|stop|restart}"
  exit 1
esac

exit $RETVAL
