#!/bin/sh
case "$1" in
  start)
	echo -n "Starting Bluetooth service: "
	cd /user/bsa
	bsa_server -d /dev/bthid 2>&1 | logger -t bsa &
	echo "done"
	;;
  stop)
	echo -n "Shutting down Bluetooth service: "
	pkill -x bsa_server
	echo "done"
	;;

  restart)
	$0 stop; sleep 2; $0 start
	;;
  *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?
