#!/bin/sh
#
# Start the network....
#

case "$1" in
  start)
	echo "Starting network..."
	cmdline=$(grep nfsroot /proc/cmdline)
	if [ $? != 0 ]; then
		echo -n "Creating bridge... "
		brctl addbr br0 || exit 1
		brctl setfd br0 1 || exit 1
		brctl stp br0 on || exit 1
		echo "done"

		echo "Adding interfaces... "
		# set up networking if we are not on an NFS rootfs
		for x in `ls /sys/class/net`; do
			ifdown $x
			echo "Configuring $x interface"
			ifup $x
			if [ -e /sys/class/net/$x/device ]; then
				brctl addif br0 $x
			fi
		done

		echo -n "Bringing up the bridge... "
		ifup br0
		echo "done"
		# Start ISC DHCP client on bridge
		/usr/sbin/dhclient br0
	else
		# just configure loopback
		/sbin/ifup lo

		# Start ISC DHCP client only on eth0
		/usr/sbin/dhclient eth0
	fi

	# Set up MoCA link, if present
	[ -e /dev/bmoca0 ] && mocacfg boot

	;;
  stop)
	echo -n "Stopping network..."
	/sbin/ifdown -a
	if ifconfig br0 >& /dev/null; then
		brctl delbr br0
	fi
	/usr/sbin/dhclient -r
	;;
  restart|reload)
	"$0" stop
	"$0" start
	;;
  *)
	echo $"Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
