#!/bin/sh
#
# Start the network....
#
SERVICE='mocad'

case "$1" in
  start)
	echo "Starting network..."
	# configure loopback
	/sbin/ifup lo
	cmdline=$(grep nfsroot /proc/cmdline)
	if [ $? != 0 ]; then
		echo -n "Creating bridge... "
		brctl addbr br0 || exit 1
		brctl setfd br0 1 || exit 1
		brctl stp br0 on || exit 1
		echo "done"

		echo "Adding interfaces... "
		# set up networking if we are not on an NFS rootfs
		for x in $(ls /sys/class/net); do
			if [ -e /sys/class/net/$x/device ]; then
				ifdown $x
				echo "Configuring $x interface"
				ifup $x
				brctl addif br0 $x
			fi
		done
		sleep 1
		echo -n "Bringing up the bridge... "
		ifup br0
		echo "done"
	fi

	# Set up MoCA link -
	# 1) if present and mocad is running, issue "mocacfg restart"
	# 2) if present and mocad is not started, issue "mocacfg boot"
	if [ -e /dev/bmoca0 ]; then
		if [ -z "$(pgrep $SERVICE)" ]; then
			echo -n "mocacfg boot "
			mocacfg boot
			echo "done"
		else
			echo -n "mocacfg restart "
			mocacfg restart
			echo "done"
		fi
	fi

	;;
  stop)
	echo -n "Stopping network..."
	cmdline=$(grep nfsroot /proc/cmdline)
	if [ $? != 0 ]; then
		for x in $(ls /sys/class/net); do
			if [ -e /sys/class/net/$x/device ]; then
				ifdown $x
				echo "Configuring $x interface"
				brctl delif br0 $x
			fi
		done
	ifdown br0
	fi
	if ifconfig br0 >& /dev/null; then
		brctl delbr br0
	fi
	;;
  restart|reload)
	"$0" stop
	"$0" start
	;;
  *)
	echo $"Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
