#!/bin/sh

case "$1" in
  start)
	catawampus 2>&1 | logger -t catawampus &
	;;
  stop)
	pkill -x catawampus
	;;

  restart)
	$0 stop; sleep 2; $0 start
	;;
  *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?
