#!/bin/sh

case "$1" in
  start)
	(ntp_wait /tmp/ntp.synced; babysit 60 cwmpd) 2>&1 | logger -t cwmpd &
	;;
  stop)
	pkill -x cwmpd
	;;

  restart)
	$0 stop; sleep 2; $0 start
	;;
  *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?
