#!/bin/sh

# Check that smb.conf exists.
[ -f /etc/samba/smb.conf ] || exit 0

# Make directories.
mkdir -p /var/cache/samba /var/log/samba

start() {
	echo -n "Starting SMB services: "
	babysit 60 nmbd -DFS 2>&1 | logger -t nmbd &
	babysit 60 smbd -DFS 2>&1 | logger -t smbd &
	echo "done"
}

stop() {
	echo -n "Shutting down SMB services: "
	pkill -9 -x smbd
	pkill -9 -x nmbd
	echo "done"
}

restart() {
	stop
	start
}

reload() {
        echo -n "Reloading smb.conf file: "
	pkill -HUP -x smbd
	echo "done"
}

case "$1" in
  start)
  	start
	;;
  stop)
  	stop
	;;
  restart)
  	restart
	;;
  reload)
  	reload
	;;
  *)
	echo "Usage: $0 {start|stop|restart|reload}"
	exit 1
esac

exit $?
