#!/bin/sh
case "$1" in
  start)
	echo "Starting psstat logger."
	psstat 60 2>&1 | logger -t ps &
	;;
  stop)
	pkill psstat
	;;
  restart|reload)
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
