#!/bin/sh

case "$1" in
  start)
	babysit 60 ntpd -sd -w /tmp/ntp.synced 2>&1 | logger -t ntpd &
	;;
  stop)
	pkill -x ntpd
	;;

  restart)
	$0 stop; sleep 2; $0 start
	;;
  *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?
