#!/bin/sh
case "$1" in
  start)
	echo "Starting log uploader."
	echo "SOFTWARE_VERSION=$(cat /etc/version)" | logger -t system
	while :; do
		upload-crash-log
		sleep 300
	done 2>&1 | logger -t upload-crash-log &
	;;
  stop)
	pkill $(basename "$0")
	;;
  restart|reload)
	;;
  *)
	echo $"Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
