apiVersion: v1
kind: Service
metadata:
  name: isoping
spec:
  ports:
  - port: 4948
    protocol: UDP
    targetPort: 4948
  selector:
    app: isoping
  sessionAffinity: ClientIP
  type: LoadBalancer
