/*
 * (C) Copyright 2015 Google, Inc.
 * All rights reserved.
 *
 */

#ifndef VENDOR_GOOGLE_DIAGS_SPACECAST_SATA_H_
#define VENDOR_GOOGLE_DIAGS_SPACECAST_SATA_H_

#define SATA_CONFIG_BASE_ADDR 0x9D000000

#define SATA_CAP_REG_OFFSET 0x0
#define SATA_GHC_REG_OFFSET 0x4
#define SATA_IS_REG_OFFSET 0x8
#define SATA_PI_REG_OFFSET 0xC
#define SATA_VS_REG_OFFSET 0x10
#define SATA_CCC_CTL_REG_OFFSET 0x14
#define SATA_CCC_PORTS_REG_OFFSET 0x18
#define SATA_CAP2_REG_OFFSET 0x24
#define SATA_BISTAFR_REG_OFFSET 0xA0
#define SATA_BISTCR_REG_OFFSET 0xA4
#define SATA_BISTFCTR_REG_OFFSET 0xA8
#define SATA_BISTSR_REG_OFFSET 0xAC
#define SATA_BISTDECR_REG_OFFSET 0xB0
#define SATA_OOBR_REG_OFFSET 0xBC
#define SATA_GPCR_REG_OFFSET 0xD0
#define SATA_GPSR_REG_OFFSET 0xD4
#define SATA_TIMER1MS_REG_OFFSET 0xE0
#define SATA_GPARAM1R_REG_OFFSET 0xE8
#define SATA_GPARAM2R_REG_OFFSET 0xEC
#define SATA_PPARAMR_REG_OFFSET 0xF0
#define SATA_TESTR_REG_OFFSET 0xF4
#define SATA_VERSIONR_REG_OFFSET 0xF8
#define SATA_IDR_REG_OFFSET 0xFC
#define SATA_CONFIG_LAST_REG_OFFSET 0xFC

#define SATA_PORT0_FIRST_REG_OFFSET 0x100
#define SATA_PORT0_LAST_REG_OFFSET 0x17C

#define SATA_PORT1_FIRST_REG_OFFSET 0x180
#define SATA_PORT1_LAST_REG_OFFSET 0x1FC

#define SATA_TEST_TX_SET1_REG_OFFSET 0x198
#define SATA_TEST_TX_SET2_REG_OFFSET 0x1AC

#define SATA_TEST_RX_SET1_REG_OFFSET 0x1B8
#define SATA_TEST_RX_SET2_REG_OFFSET 0x1B4
#define SATA_TEST_RX_SET3_REG_OFFSET 0x1A0

#endif  // VENDOR_GOOGLE_DIAGS_SPACECAST_SATA_H_
