application: gfiber-dropbox
version: 2
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /upload/.*
  script: app.wsgi_app

- url: /_.*
  script: app.wsgi_app
  login: admin

- url: /.*
  script: app.wsgi_app
  login: required
