/*
 * Copyright 2016 Google Inc. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


#ifndef MODELLOOKUP_H_
#define MODELLOOKUP_H_

#ifdef __cplusplus
extern "C" {
#endif

/* Structure returned by the model_lookup function. */
struct model_strings {
  const char *model;
  const char *genus;
  const char *species;
};

/* Function generated by gperf for the model_lookup table. */
extern const struct model_strings *model_lookup(const char *str,
    unsigned int len);

#ifdef __cplusplus
}
#endif

#endif  // MODELLOOKUP_H_
