#! /bin/sh

pycode=/bin/craftui.py
cw=/usr/catawampus
devcw=../../../../vendor/google/catawampus
localwww=./www

# in developer environment if vendor/google/catawapus is above us
if [ -d "$devcw" ]; then
  isdev=1
fi

# if running from developer desktop, use simulated data
if [ "$isdev" = 1 ]; then
  cw="$devcw"
  args="$args --port=8888 --sim=./sim"
  pycode=./craftui_fortesting.py
  export PATH="$PWD/sim/bin:$PATH"
fi

# for debugging on the device, use the local (/tmp/www?) web tree
if [ -d "$localwww" ]; then
  args="$args --www=$localwww"
fi

# enable debugger
if [ "$1" = -d ]; then
  debug="-m pdb"
fi

export PYTHONPATH="$cw/tr/vendor/tornado:$PYTHONPATH"
exec python -u $debug $pycode $args
