#!/bin/sh

# NTP server handling
case $reason in
  BOUND|RENEW|REBIND|REBOOT)
    if [ "$new_ntp_servers" = "$old_ntp_servers" ]; then
      return
    fi

    if [ -z "$new_ntp_servers" ]; then
      /etc/init.d/S75ntpd restart
      return
    fi

    # Discard old servers, including those from ntpd.conf.default.
    # Use only the servers we just received via DHCP.
    (for server in $new_ntp_servers; do
      echo "server $server"
    done) >/tmp/ntpd.conf

    /etc/init.d/S75ntpd restart
    ;;

  EXPIRE|FAIL|RELEASE|STOP)
    cp /etc/ntpd.conf.default /tmp/ntpd.conf
    /etc/init.d/S75ntpd restart
    ;;
esac
